import { signOut } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div className="bg-[#f3f2ef] dark:bg-black dark:text-white h-screen overflow-scroll md:space-y-6">
      <Head>
        <title>Feed | LinkedIn Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Next LinkedIn Clone
      <button onClick={signOut}>Sign out</button> */}
      <Header />
      <main className="flex justify-center gap-x-5 px-4 sm:px-12">
        <div className="flex flex-col md:flex-row gap-5">
          <Sidebar />
          {/* feed */}
        </div>
        {/* widgets */}
      </main>
    </div>
  );
}
